server:
  port: 8080
spring:
  resources:
    static-locations: classpath:/static
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 19940904997
          url: jdbc:mysql://127.0.0.1:3306/jeeplus-boot-4?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
          driver-class-name : com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzp.vuespringbootmybatis.mapper